name: Generate CBOM
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate CBOM
        uses: cbomkit/cbomkit-action@v2
        env:
          CBOMKIT_LANGUAGES: python

      - name: Upload CBOM Result
        uses: actions/upload-artifact@v4
        with:
          name: "CBOM-Report"
          path: "cbom/"
